<div id="ameriquote_body">

        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
                <form data-bind="submit: getQuotes">
                    <div class="tile params clearfix">
                        <h3 class="tile-title">Get Instant Real-time Quotes</h3>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">Smoker?</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 text-left smoker">
                                
                                <label class="radio">
                                    Yes&nbsp;
                                    <input type="radio" data-toggle="radio" data-radiocheck-toggle="radio" name="Smoker" value="Y">
                                </label>
                                <label class="radio">No
                                    <input type="radio" data-toggle="radio" name="Smoker" checked data-radiocheck-toggle="radio" value="N">
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">State</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 pull-left">

                                <select name="State" size="1" data-toggle="select" class="form-control select select-primary mrs mbm pull-left ">
                                    <option value="1">Alabama</option>
                                    <option value="2">Alaska</option>
                                    <option value="3">Arizona</option>
                                    <option value="4">Arkansas</option>
                                    <option selected value="5">California</option>
                                    <option value="6">Colorado</option>
                                    <option value="7">Connecticut</option>
                                    <option value="8">Delaware</option>
                                    <option value="9">Dist.Columbia</option>
                                    <option value="10">Florida</option>
                                    <option value="11">Georgia</option>
                                    <option value="12">Hawaii</option>
                                    <option value="13">Idaho</option>
                                    <option value="14">Illinois</option>
                                    <option value="15">Indiana</option>
                                    <option value="16">Iowa</option>
                                    <option value="17">Kansas</option>
                                    <option value="18">Kentucky</option>
                                    <option value="19">Louisiana</option>
                                    <option value="20">Maine</option>
                                    <option value="21">Maryland</option>
                                    <option value="22">Massachusetts</option>
                                    <option value="23">Michigan</option>
                                    <option value="24">Minnesota</option>
                                    <option value="25">Mississippi</option>
                                    <option value="26">Missouri</option>
                                    <option value="27">Montana</option>
                                    <option value="28">Nebraska</option>
                                    <option value="29">Nevada</option>
                                    <option value="30">New Hampshire</option>
                                    <option value="31">New Jersey</option>
                                    <option value="32">New Mexico</option>
                                    <option value="52">NY Non-Bus</option>
                                    <option value="33">NY Business</option>
                                    <option value="34">North Carolina</option>
                                    <option value="35">North Dakota</option>
                                    <option value="36">Ohio</option>
                                    <option value="37">Oklahoma</option>
                                    <option value="38">Oregon</option>
                                    <option value="39">Pennsylvania</option>
                                    <option value="40">Rhode Island</option>
                                    <option value="41">South Carolina</option>
                                    <option value="42">South Dakota</option>
                                    <option value="43">Tennessee</option>
                                    <option value="44">Texas</option>
                                    <option value="45">Utah</option>
                                    <option value="46">Vermont</option>
                                    <option value="47">Virginia</option>
                                    <option value="48">Washington</option>
                                    <option value="49">West Virginia</option>
                                    <option value="50">Wisconsin</option>
                                    <option value="51">Wyoming</option>
                                    <option value="53">Guam</option>
                                    <option value="54">Puerto Rico</option>
                                    <option value="55">Virgin Islands</option>
                                    <option value="56">Amer. Samoa</option>
                                </select>

                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">Birthdate</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 birthdate">



                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <select name="BirthMonth" data-toggle="select" class="form-control select select-primary mrs mbm pull-left">
                                        <option value="1">January</option>
                                        <option value="2">February</option>
                                        <option value="3">March</option>
                                        <option value="4">April</option>
                                        <option value="5">May</option>
                                        <option selected value="6">June</option>
                                        <option value="7">July</option>
                                        <option value="8">August</option>
                                        <option value="9">September</option>
                                        <option value="10">October</option>
                                        <option value="11">November</option>
                                        <option value="12">December</option>
                                    </select>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <select name="Birthday" data-toggle="select" class="form-control select select-primary mrs mbm pull-left">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                        <option>6</option>
                                        <option>7</option>
                                        <option>8</option>
                                        <option>9</option>
                                        <option>10</option>
                                        <option>11</option>
                                        <option>12</option>
                                        <option>13</option>
                                        <option>14</option>
                                        <option selected>15</option>
                                        <option>16</option>
                                        <option>17</option>
                                        <option>18</option>
                                        <option>19</option>
                                        <option>20</option>
                                        <option>21</option>
                                        <option>22</option>
                                        <option>23</option>
                                        <option>24</option>
                                        <option>25</option>
                                        <option>26</option>
                                        <option>27</option>
                                        <option>28</option>
                                        <option>29</option>
                                        <option>30</option>
                                        <option>31</option>
                                    </select>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <select name="BirthYear" data-toggle="select" class="form-control select select-primary mrs mbm pull-left">
                                        <option>1910</option>
                                        <option>1911</option>
                                        <option>1912</option>
                                        <option>1913</option>
                                        <option>1914</option>
                                        <option>1915</option>
                                        <option>1916</option>
                                        <option>1917</option>
                                        <option>1918</option>
                                        <option>1919</option>
                                        <option>1920</option>
                                        <option>1921</option>
                                        <option>1922</option>
                                        <option>1923</option>
                                        <option>1924</option>
                                        <option>1925</option>
                                        <option>1926</option>
                                        <option>1927</option>
                                        <option>1928</option>
                                        <option>1929</option>
                                        <option>1930</option>
                                        <option>1931</option>
                                        <option>1932</option>
                                        <option>1933</option>
                                        <option>1934</option>
                                        <option>1935</option>
                                        <option>1936</option>
                                        <option>1937</option>
                                        <option>1938</option>
                                        <option>1939</option>
                                        <option>1940</option>
                                        <option>1941</option>
                                        <option>1942</option>
                                        <option>1943</option>
                                        <option>1944</option>
                                        <option>1945</option>
                                        <option>1946</option>
                                        <option>1947</option>
                                        <option>1948</option>
                                        <option>1949</option>
                                        <option>1950</option>
                                        <option>1951</option>
                                        <option>1952</option>
                                        <option>1953</option>
                                        <option>1954</option>
                                        <option>1955</option>
                                        <option>1956</option>
                                        <option>1957</option>
                                        <option>1958</option>
                                        <option>1959</option>
                                        <option>1960</option>
                                        <option>1961</option>
                                        <option>1962</option>
                                        <option>1963</option>
                                        <option>1964</option>
                                        <option>1965</option>
                                        <option>1966</option>
                                        <option>1967</option>
                                        <option>1968</option>
                                        <option>1969</option>
                                        <option selected>1970</option>
                                        <option>1971</option>
                                        <option>1972</option>
                                        <option>1973</option>
                                        <option>1974</option>
                                        <option>1975</option>
                                        <option>1976</option>
                                        <option>1977</option>
                                        <option>1978</option>
                                        <option>1979</option>
                                        <option>1980</option>
                                        <option>1981</option>
                                        <option>1982</option>
                                        <option>1983</option>
                                        <option>1984</option>
                                        <option>1985</option>
                                        <option>1986</option>
                                        <option>1987</option>
                                        <option>1988</option>
                                        <option>1989</option>
                                        <option>1990</option>
                                        <option>1991</option>
                                        <option>1992</option>
                                        <option>1993</option>
                                        <option>1994</option>
                                        <option>1995</option>
                                        <option>1996</option>
                                        <option>1997</option>
                                        <option>1998</option>
                                        <option>1999</option>
                                        <option>2000</option>
                                        <option>2001</option>
                                        <option>2002</option>
                                        <option>2003</option>
                                        <option>2004</option>
                                        <option>2005</option>
                                        <option>2006</option>
                                        <option>2007</option>
                                        <option>2008</option>
                                    </select>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">Gender</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 text-left gender">
                                <label class="radio">
                                    Male&nbsp;
                                    <input type="radio" data-toggle="radio" data-radiocheck-toggle="radio" checked name="Sex" value="M">
                                </label>
                                <label class="radio">Female
                                    <input type="radio" data-toggle="radio" name="Sex" data-radiocheck-toggle="radio" value="F">
                                </label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">Term</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 text-left term">
                                <select name="NewCategory" data-toggle="select" class="form-control select select-primary mrs mbm pull-left">
                                    <option value="1">1 Year Level Term</option>
                                    <option value="2">5 Year Level Term</option>
                                    <option value="3">10 Year Level Term</option>
                                    <option value="4">15 Year Level Term</option>
                                    <option SELECTED value="5">20 Year Level Term</option>
                                    <option value="6">25 Year Level Term</option>
                                    <option value="7">30 Year Level Term</option>
                                    <!--<option value="9">35 Year Level Term</option>
<option value="0">40 Year Level Term</option>-->
                                    <option value="T">To Age 65 Level</option>
                                    <option value="U">To Age 70 Level</option>
                                    <option value="V">To Age 75 Level</option>
                                    <option value="A">To Age 80 Level</option>
                                    <option value="B">To Age 85 Level</option>
                                    <option value="C">To Age 90 Level</option>
                                    <option value="D">To Age 95 Level</option>
                                    <option value="E">To Age 100 Level</option>
                                    <option value="G">To Age 105 Level</option>
                                    <option value="H">To Age 110 Level</option>
                                    <option value="Z:1234567TUVABCDEGH">All Level Term Products</option>
                                </select>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">Face Amount</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 text-left faceamount">
                                <select name="FaceAmount" size="1" data-toggle="select" class="form-control select select-primary mrs mbm pull-left">
                                    <option value="10000">$10,000</option>
                                    <option value="25000">$25,000</option>
                                    <option value="50000">$50,000</option>
                                    <option value="50000" selected=selected>$50,000</option>
                                    <option value="75000">$75,000</option>
                                    <option value="100000">$100,000</option>
                                    <option value="125000">$125,000</option>
                                    <option value="150000">$150,000</option>
                                    <option value="175000">$175,000</option>
                                    <option value="200000">$200,000</option>
                                    <option value="225000">$225,000</option>
                                    <option value="250000">$250,000</option>

                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 text-left">Health Class</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 text-left smoker">
                                <select name="Health" size="1" data-toggle="select" class="form-control select select-primary mrs mbm pull-left">
                                    <option selected value="PP">Preferred Plus</option>
                                    <option value="P">Preferred</option>
                                    <option value="RP">Regular Plus</option>
                                    <option value="R">Regular</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-3 hidden-sm hidden-xs">&nbsp;</div>
                            <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 text-left">
                                <button type="submit" class="btn btn-primary">Compare Now</button></form>
                            </div>
                        </div>


                    </div>

            </div>

            <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                <div class="lander"></div>
                 <div id="sorts" class="button-group row" data-bind="visible: results">
                     <div class="sort col-lg-2 col-md-2 col-sm-12 col-xs-12">Sort By:</div>
                     <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                      <div class="btn btn-info btn-inverse" data-sort-by="premium">Premium</div>
                        <div class="btn btn-info" data-sort-by="company">Company</div>
  
                        <div class="btn btn-info" data-sort-by="health">Health Category</div>   
                     </div>



</div>
                <div class="no-results" data-bind="visible: !results">Sorry. There are no results for your result. Please make changes to your search and try again.</div>
                <div class="results">
                   
                    <div class="results-grid" data-bind="foreach: quotes">
                        
                        <div class="quote tile" data-bind="attr: {id: product_code+health_code, 'data-company': company_code, 'data-premium': monthly, 'data-health': health_category}">
                            <div class="logo-pic"><span class="helper"></span><img data-bind="attr: { src: 'http://quotes.ameriquote.com/wp-content/plugins/ameriquote/logos/'+company_code+'.gif'}" align="center">
                            <span class="monthly"><span data-bind="text: monthly"></span>/month</span>
                            </div>
                            
                            <div class="product_name"><label>Product:</label> <span data-bind="text: product_name"></span></div>
                            <div class="company_name" ><label>Company:</label><span data-bind="text: company_name"></span></div>
                              <div class="health_category"><label>Health Category:</label> <span data-bind="text: health_category"></span></div>
                            
                            <div class="coverage"><label>Coverage:</label> <span data-bind="text: face_amount"></span></div>
                           <div class="footer-icons">
                               <div class="icon"><div class="fa fa-phone-square fa-3x call" data-toggle="tooltip" data-placement="bottom" data-bind="attr: { title: 'Call Agent to Apply-(' + format_telephone(phone)[1]+')'+format_telephone(phone)[2]+'-'+format_telephone(phone)[3]}, click: $parent.callAgent"></div>
                               <div class="hidden-sm hidden-lg hidden-md">Call Agent</div></div>
                               <div class="icon"><div class="fa fa-heart fa-3x save" data-bind="click: $parent.saveQuote" data-toggle="tooltip" data-placement="bottom" title="Save for Comparison Grid"></div>
                               <div class="hidden-sm hidden-lg hidden-md">Save</div></div>
                               <div class="icon"><div class="fa fa-book fa-3x company" data-bind="click: $parent.getCompany" data-toggle="tooltip" data-placement="bottom" title="Read About Company"></div>
                               <div class="hidden-sm hidden-lg hidden-md">Company Info</div></div>
                               <div class="icon"><div class="fa fa-user fa-3x request" data-toggle="tooltip" data-bind="click: $parent.showForm" data-placement="bottom" title="Have an Ameriquote Agent Contact You"></div>
                               <div class="hidden-sm hidden-lg hidden-md">Apply</div></div>
                   
                           </div>
                                <div class="apply-form well">
                                    <p>Fill out the form below and an Agent will contact you with your exclusive quote.</p>
                                   <form data-bind="submit: $parent.postLead">
                                       <input type="text" name="firstname" placeholder="First Name">
                                       <input type="text" name="lastname" placeholder="Last Name">
                                       <input type="email" name="email" placeholder="Email Address">
                                       <input type="tel" name="phone" placeholder="Home Phone">
                                       <input type="text" name="zipcode" placeholder="Zipcode">
                                       <input type="hidden" name="face_amount" data-bind="attr: {value: face_amount}">
                                       <input type="hidden" name="coverage_term" data-bind="attr: {value: new_category}">
                                        <input type="hidden" name="company_name" data-bind="attr: {value: company_name}">
                                         <input type="hidden" name="product_name" data-bind="attr: {value: product_name}">
                                         <input type="hidden" name="product_code" data-bind="attr: {value: product_code}">
                                         <input type="hidden" name="health_code" data-bind="attr: {value: health_code}">
                                       <button type="submit" class="btn btn-primary">Submit</button>
                                   </form>
                                   
                                   
                               </div>
                        
                        </div>

                    
                    </div>
                </div>

            </div>

            
        </div>


</div>
<div data-bind="visible: company, with: company" class="company-pop modal fade">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header clearfix">
          <div class="row">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>            
          </div>
<div class="row">
    <div class="col-lg-4"><div class="company-logo"><img data-bind="attr: { src: featured_image}" align="center"></div></div>
    <div class="col-lg-8"><h4 class="modal-title" id="myModalLabel" data-bind="text: company_name"></h4></div>
</div>
        
      </div>
      <div class="modal-body">
    
    <div class="company-name" ></div>
        <div class="company-content" data-bind="html: content"></div>
    </div>
    </div>
    </div>
</div>

<div class="call-pop modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header clearfix">
              <div class="row">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>  
              </div>
    
            <div class="icon"><div class="fa fa-phone-square"></div></div><h4 class="modal-title" id="myModalLabel">Call an Agent</h4>
          </div>
            <div class="modal-body">
               <div class="desktop-contact">Call <span data-bind="text: '(' + format_telephone(ameriquote_phone)[1]+')'+format_telephone(ameriquote_phone)[2]+'-'+format_telephone(ameriquote_phone)[3]"></span> to speak to an agent</div>
               <div class="mobile-contact">Click <a data-bind="attr: {href:'tel://'+call_agent()}" ><span data-bind="text: '(' + format_telephone(ameriquote_phone)[1]+')'+format_telephone(ameriquote_phone)[2]+'-'+format_telephone(ameriquote_phone)[3]"></span></a> to launch your dialer and call. </div>
            </div>
        </div>
    </div>
</div>






